<?php

namespace AppBundle\Repository;

/**
 * BenevolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BenevolesRepository extends \Doctrine\ORM\EntityRepository
{
}
