<?php

namespace AppBundle\Repository;

/**
 * EvenementBenevoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementBenevoleRepository extends \Doctrine\ORM\EntityRepository
{
}
