<?php

namespace AppBundle\Repository;

/**
 * MediasEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediasEventRepository extends \Doctrine\ORM\EntityRepository
{
}
