<?php

namespace AppBundle\Repository;

/**
 * MediasSportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediasSportRepository extends \Doctrine\ORM\EntityRepository
{
}
