<?php

namespace AppBundle\Repository;

/**
 * MediasClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediasClubRepository extends \Doctrine\ORM\EntityRepository
{
}
