<?php

namespace AppBundle\Repository;

/**
 * MediasUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediasUserRepository extends \Doctrine\ORM\EntityRepository
{
}
