<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class UserRepository extends EntityRepository
{
	// On verra plus tard
	// public function getValidSport()
	// {
	// 	$queryBuilder = $this->createQueryBuilder('sportValid');
	// 	$queryBuilder
	// 		->select('sportValid')
	// 		->innerJoin('AppBundle:Sport', 'sp', 'WITH', 'sp.id = c.id')
 //        ->orderBy('c.createdAt', 'DESC')
 //        ->where('co.group = :group OR ct.group = :group')
 //        ->setParameter('group', $group)
 //        ->setMaxResults(20);

	// 	->where('sportValid.confirmAdmin = :confirmAdmin')
	// 					->setParameter('confirmAdmin', $adminValue);


	// 	return "test";
	// }
}
