asp_admin_sport:
    resource: "@ASPAdminSportBundle/Controller/"
    type:     annotation
    prefix:   /adminSport

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile_edit:
    path: /user
    defaults: { _controller: FOSUserBundle:Profile:edit }
    requirements:
        _method: GET|POST
