<?php

namespace ASP\AdminSportBundle\Repository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository

class ClubRepository extends EntityRepository
{
	public function clubAdminNoValid()
	{
		$adminValue = 0;

		$queryBuilder = $this->createQueryBuilder('clubNoValid');
		$queryBuilder->where('clubNoValid.confirm_admin = :confirm_admin')
						->setParameter('confirm_admin', $adminValue);

		$query = $queryBuilder->getQuery();

		$results = $query->getResult();

		return $results;
	}
}
